const APIGatewayRequest = ({
    body,
    method,
    path = '',
    queryStringObject,
    pathParametersObject,
    stageVariables = null,
    headers = {},
    multiValueHeaders = {},
    isBase64Encoded = false,
    requestTimeEpoch = Math.floor(new Date().getTime() / 1000),
    resource = 'your-resource-path',
}) => {
    const request = {
        body: body ? JSON.stringify(body) : null,
        headers,
        multiValueHeaders,
        httpMethod: method,
        isBase64Encoded,
        path,
        pathParameters: pathParametersObject || null,
        queryStringParameters: queryStringObject || null,
        multiValueQueryStringParameters: null,
        stageVariables,
        requestContext: {
            accountId: '',
            apiId: '',
            httpMethod: method,
            identity: {
                accessKey: '',
                accountId: '',
                apiKey: '',
                apiKeyId: '',
                caller: '',
                cognitoAuthenticationProvider: '',
                cognitoAuthenticationType: '',
                cognitoIdentityId: '',
                cognitoIdentityPoolId: '',
                principalOrgId: '',
                sourceIp: '',
                user: '',
                userAgent: '',
                userArn: '',
            },
            path,
            stage: '',
            requestId: '',
            requestTimeEpoch,
            resourceId: '',
            resourcePath: '',
        },
        resource,
    };
    return request;
};

module.exports = APIGatewayRequest;
